trigger:
  tags:
    include:
    - 'v*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: npm install
  displayName: 'npm install'

- script: npm run test
  displayName: 'Run tests'

- script: npm run build
  displayName: 'npm run build'

- script: |
    echo "//registry.npmjs.org/:_authToken=$(NPM_TOKEN)" > lib/.npmrc
    cd lib
    npm publish
  displayName: 'Publish to npm'
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
  env:
    NPM_TOKEN: $(NPM_TOKEN)
